server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web-dev-db
    username: root
    password: my-secret-pw
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    show-sql: true

stripe:
  secret:
    key: sk_test_51IjpywIWp3VgGAPO4lrvvPgRXeMyz0WMpy2I5BQtsXyOeAENe6rFjisiQYLp5OiHSHxZTMUf5idrdq3idKnaOnNJ00ustH6LpR